BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Todo` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Title`	TEXT NOT NULL,
	`Description`	TEXT,
	`DateTime`	NUMERIC NOT NULL,
	`Complete`	NUMERIC NOT NULL
);
COMMIT;
